name: Integration

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          check-latest: true
      - run: npm install
      - run: npm run lint
